---
- hosts:              webservers
  gather_facts:       no
  tasks:
    - name:           Add Node apt-repository
      apt_repository: repo='ppa:chris-lea/node.js' state=present
      sudo:           yes

    - name:           Update apt repositories
      apt:            update_cache=yes
      sudo:           yes

    - name:           Install system packages
      apt:            pkg=nodejs
      sudo:           yes
